import Head from "next/head";
import Image from "next/image";
import { motion } from "framer-motion";
import Router, { useRouter } from "next/router";
// style
import styles from "../styles/Home.module.css";
// icons
import logo from "../public/logo.svg";
import image2 from "../public/image2.svg";
import image4 from "../public/image4.svg";
import Group10 from "../public/whatsapp.svg";
import ImageAdvWhy from "../public/ImageWhy2.svg";
import titles from "../assets/titles";
export default function Home() {
  const router = useRouter();
  return (
    <motion.div
      className={styles.container}
      initial="hidden"
      animate="visible"
      variants={{
        hidden: {
          scale: 0.8,
          opacity: 0,
        },
        visible: {
          scale: 1,
          opacity: 1,
          transition: {
            delay: 1,
          },
        },
      }}
    >
      <Head>
        <title>Hike</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header style={{backgroundColor:"#fefefe"}} className={styles.header}>
        <div className={styles.navbar}>
          <Image src={logo} alt="Vercel Logo" width={120} height={60} />
          <a
            style={{
              display: "flex",
              flexDirection: "row",
              alignItems: "center",
              marginTop: "-10px",
            }}
            href="https://wa.me/+96181042312"
          >
            <Image
              src={Group10}
              alt="Vercel Logo"
              height={60}
              color="#000"
              style={{
                backgroundColor: "#28D045",
                borderRadius: "50%",
                padding: ".6rem",
                borderWidth: "3px",
                borderColor: "#F1F1F1",
                borderStyle: "solid",
                marginRight: "1rem",
              }}
              onClick={() => {
                "whatsapp://send?abid=+961 81 042 312&text=Hello%2C%20World!";
              }}
            />
            <p
              className={styles.titleHeader}
              style={{
                fontSize: ".8rem",
                marginTop: "1rem",
              }}
            >
              We are online
            </p>
          </a>
        </div>
      </header>

      {/* why 2 */}
      <main className={styles.main} style={{ marginTop: "4vh" }}>
        <div className={styles.leftHalfSection}>
          <div className={styles.containerLeftSection}>
            <p className={styles.title1InCOntainerLeftSec}>{titles.header}.</p>
            <p className={styles.title2IncontainerLeftSec}>{titles.body}</p>
            <div style={{ flexDirection: "row", width: "100%" }}>
              <Image
                className={styles.btnDownloadMain}
                src={image2}
                alt="Vercel Logo"
                width={"100%"}
                height={"100%"}
                style={{
                  backgroundColor: "transparent",
                  border: 0,
                  borderRadius: 0,
                }}
              />
              <Image
                className={styles.btnDownloadMain}
                style={{
                  backgroundColor: "transparent",
                  border: 0,
                  borderRadius: 0,
                }}
                src={image4}
                alt="Vercel Logo"
                width={"100%"}
                height={"100%"}
              />
            </div>
          </div>
        </div>
        <div
          className={styles.rightHalfSection}
          style={{
            backgroundColor: "#E6F8F8",
          }}
        >
          <Image
            src={ImageAdvWhy}
            alt="Vercel Logo"
            className={styles.ImageAdvWhy}
            style={{ objectFit: "scale-down" }}
            layout="fill"
            objectFit="cover"
          />
        </div>
      </main>
      <footer className={styles.footer}>
        {titles.footer}
        <button
          style={{
            border: "0",
            textUnderlinePosition: "under",
            textUnderlineOffset: "1",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            backgroundColor: "transparent",
          }}
          onClick={() => {
            router.push("/privacy");
          }}
        >
          {"\t   "}privacy
        </button>
      </footer>
    </motion.div>
  );
}
